var ads = function(){
var link_ads = [
    'https://shope.ee/3pmTwAtJ7S',
    'https://shope.ee/3fT3jrtwSR',
    'https://shope.ee/2ptwkKx79I',
    'https://shope.ee/2faWY1xkUH',
    'https://shope.ee/3AWn8wvqTO',
    'https://shope.ee/30DMwdwToN',
    'https://shope.ee/4pf180pV5k',
    'https://shope.ee/4fLavhq8Qj',
    'https://shope.ee/5AHrWcoEPq',
    'https://shope.ee/4zyRKJorkp',
    'https://shope.ee/4APKKms2Rg',
    'https://shope.ee/405u8Tsfmf',
    'https://tokopedia.link/3CWEpyYpdub',
    'https://tokopedia.link/LSPyLIZpdub',
    'https://tokopedia.link/Q9fv2L0pdub',
    'https://tokopedia.link/wqHC4Q1pdub',
    'https://tokopedia.link/1OmcWZ2pdub',
    'https://tokopedia.link/K37JA83pdub',
    'https://tokopedia.link/W5hOWs5pdub',
    'https://tokopedia.link/LOwn0A6pdub',
    'https://tokopedia.link/oQBLZO7pdub',
    'https://tokopedia.link/dAsdCU8pdub',
    'https://tokopedia.link/6ak2Ocaqdub',
    'https://shope.ee/4V0P2vy8LR',
    'https://shope.ee/7ez1iF1OMb',
    'https://shope.ee/5pWRQbryzY',
    'https://shope.ee/1L4yAeg1jc',
    'https://shope.ee/3Kp6S5QQ6d',
    'https://shope.ee/9K7FhHmJ9M',
    'https://tokopedia.link/XCihkticTub',
    'https://tokopedia.link/nrSsahxAKub',
    'https://tokopedia.link/h1rtv2zAKub',
];
var max_ads = (link_ads.length)
window.open(link_ads[Math.floor(Math.random()*max_ads)]);
};