var ads = function(){
var link_ads = [
'https://shope.ee/5KcJjUCTrN',
'https://shope.ee/3V7d9HHAod',
'https://shope.ee/30BMYMJ4pY',
'https://shope.ee/1L4yAeg1jc',
'https://shope.ee/30BSncdLMK',
'https://shope.ee/3AUszvci1N',
'https://shope.ee/2fYcP0ec2I',
'https://shope.ee/2ps2bJdyhL',
'https://shope.ee/4zwXBIVjIm',
'https://shope.ee/5AFxOe4q2g',
'https://shope.ee/4zwXCL5TNf',
'https://shope.ee/2ps2cMDimG',
'https://shope.ee/2fYcQ3EM7F',
'https://shope.ee/3AUt0yCS6M',
'https://shope.ee/7KKRycwaeL',
'https://shope.ee/7pGiZXugdS',
'https://shope.ee/7exINEvJyR',
'https://shope.ee/5UsnnG3ZN2',
'https://shope.ee/5KZNax4Ci1',
'https://tokopedia.link/rXwopozItvb',
'https://tokopedia.link/CBfB7lrItvb',
'https://tokopedia.link/dipSHWAAKub',
'https://tokopedia.link/n25IxUBAKub',
'https://tokopedia.link/aZ3GnMCAKub',
'https://tokopedia.link/rKwX5uDAKub',
'https://tokopedia.link/XL4m7rEAKub',
'https://tokopedia.link/VliU3gFAKub',
'https://tokopedia.link/gXjQA9FAKub',
'https://tokopedia.link/x5tmrTGAKub',
];
var max_ads = (link_ads.length)
window.open(link_ads[Math.floor(Math.random()*max_ads)]);
};